Repository Nexters/Linkllet-Server, pull requests merged in 2023-07, with the labels that each got.

#2 feat: 도메인 설정
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/config/JpaAuditingConfiguration.kt
  src/main/kotlin/nexters/linkllet/domain/Article.kt
  src/main/kotlin/nexters/linkllet/domain/BaseTimeEntity.kt
  src/main/kotlin/nexters/linkllet/domain/Link.kt
  src/main/kotlin/nexters/linkllet/domain/Member.kt
  src/main/kotlin/nexters/linkllet/domain/Tag.kt
  src/test/kotlin/nexters/linkllet/domain/ArticleTest.kt
  src/test/resources/application.yml
Labels: 🚀 기능 구현 🚀

#4 feat: 회원 관련 API를 구현한다
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/controller/MemberController.kt
  src/main/kotlin/nexters/linkllet/domain/Article.kt
  src/main/kotlin/nexters/linkllet/domain/Member.kt
  src/main/kotlin/nexters/linkllet/domain/Tag.kt
  src/main/kotlin/nexters/linkllet/dto/MemberDtos.kt
  src/main/kotlin/nexters/linkllet/repository/MemberRepository.kt
  src/main/kotlin/nexters/linkllet/service/MemberService.kt
  src/main/resources/application.yml
  src/test/kotlin/nexters/linkllet/acceptance/AcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/DatabaseCleaner.kt
  src/test/kotlin/nexters/linkllet/acceptance/DatabaseCleanerCallback.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberAcceptanceTest.kt
Labels: 🚀 기능 구현 🚀, 🔭 테스트 🔭

#9 feat: 도메인 구조를 폴더를 사용하도록 변경
  src/main/kotlin/nexters/linkllet/article/domain/Article.kt
  src/main/kotlin/nexters/linkllet/article/domain/Articles.kt
  src/main/kotlin/nexters/linkllet/article/domain/Link.kt
  src/main/kotlin/nexters/linkllet/common/domain/BaseTimeEntity.kt
  src/main/kotlin/nexters/linkllet/domain/Article.kt
  src/main/kotlin/nexters/linkllet/domain/Member.kt
  src/main/kotlin/nexters/linkllet/domain/Tag.kt
  src/main/kotlin/nexters/linkllet/folder/domain/Folder.kt
  src/main/kotlin/nexters/linkllet/member/domain/Member.kt
  src/main/kotlin/nexters/linkllet/member/domain/MemberRepository.kt
  src/main/kotlin/nexters/linkllet/member/dto/MemberDtos.kt
  src/main/kotlin/nexters/linkllet/member/presentation/MemberController.kt
  src/main/kotlin/nexters/linkllet/member/service/MemberService.kt
  src/main/kotlin/nexters/linkllet/service/MemberService.kt
  src/test/kotlin/nexters/linkllet/acceptance/DatabaseCleaner.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/domain/article/ArticleTest.kt
  src/test/kotlin/nexters/linkllet/domain/folder/FolderTest.kt
Labels: 🚀 기능 구현 🚀, 🔭 테스트 🔭

#13 feat: 디바이스 헤더 추출 기능 구현
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/article/domain/Articles.kt
  src/main/kotlin/nexters/linkllet/common/support/AccessDeviceId.kt
  src/main/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractor.kt
  src/main/kotlin/nexters/linkllet/common/support/DeviceUserResolver.kt
  src/main/kotlin/nexters/linkllet/config/WebMvcConfiguration.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderCommandApi.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderQueryApi.kt
  src/test/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractorTest.kt
  src/test/resources/application.yml
Labels: 🚀 기능 구현 🚀

#14 feat: Swagger API 자동 문서화 설정
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/common/support/AccessDeviceId.kt
  src/main/kotlin/nexters/linkllet/config/SwaggerConfiguration.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderCommandApi.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderQueryApi.kt
  src/main/kotlin/nexters/linkllet/member/presentation/MemberCommandApi.kt
  src/main/resources/application.yml
Labels: 📖 문서화 📖, 🚀 기능 구현 🚀

#16 feat: 예외 핸들링 기능 구현
  src/main/kotlin/nexters/linkllet/article/domain/Articles.kt
  src/main/kotlin/nexters/linkllet/article/domain/Link.kt
  src/main/kotlin/nexters/linkllet/common/exception/CommonExceptionHandler.kt
  src/main/kotlin/nexters/linkllet/common/exception/dto/ErrorDtos.kt
  src/main/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractor.kt
  src/main/kotlin/nexters/linkllet/folder/domain/Folder.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderRepository.kt
  src/main/kotlin/nexters/linkllet/folder/service/FolderService.kt
  src/main/kotlin/nexters/linkllet/member/domain/MemberRepository.kt
  src/test/kotlin/nexters/linkllet/acceptance/ArticleAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractorTest.kt
  src/test/kotlin/nexters/linkllet/domain/article/ArticleTest.kt
  src/test/kotlin/nexters/linkllet/domain/folder/FolderTest.kt
Labels: 🚀 기능 구현 🚀

#17 fix: validate duplicated device id
  src/main/kotlin/nexters/linkllet/common/exception/dto/ErrorDtos.kt
  src/main/kotlin/nexters/linkllet/member/service/MemberService.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberAcceptanceTest.kt
Labels: ❗️버그❗️

#21 feat: 폴더명 변경 기능 및 폴더명/링크제목 10자 이하 검증 추가
  src/main/kotlin/nexters/linkllet/article/domain/Article.kt
  src/main/kotlin/nexters/linkllet/folder/domain/Folder.kt
  src/main/kotlin/nexters/linkllet/folder/dto/FolderDtos.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderCommandApi.kt
  src/main/kotlin/nexters/linkllet/folder/service/FolderService.kt
  src/test/kotlin/nexters/linkllet/acceptance/ArticleAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/FolderAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/FolderStep.kt
  src/test/kotlin/nexters/linkllet/domain/article/ArticleTest.kt
  src/test/kotlin/nexters/linkllet/domain/folder/FolderTest.kt
Labels: 🚀 기능 구현 🚀, 🎲 API 변경 🎲

#23 feat: MemberService 에서 커스텀 폴더 2개도 추가 생성되도록 구현
  src/main/kotlin/nexters/linkllet/member/service/MemberService.kt
Labels: 🚀 기능 구현 🚀

#24 version 1.0.0
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/article/domain/Article.kt
  src/main/kotlin/nexters/linkllet/article/domain/Articles.kt
  src/main/kotlin/nexters/linkllet/article/domain/Link.kt
  src/main/kotlin/nexters/linkllet/common/domain/BaseTimeEntity.kt
  src/main/kotlin/nexters/linkllet/common/exception/CommonExceptionHandler.kt
  src/main/kotlin/nexters/linkllet/common/exception/dto/ErrorDtos.kt
  src/main/kotlin/nexters/linkllet/common/support/AccessDeviceId.kt
  src/main/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractor.kt
  src/main/kotlin/nexters/linkllet/common/support/DeviceUserResolver.kt
  src/main/kotlin/nexters/linkllet/config/JpaAuditingConfiguration.kt
  src/main/kotlin/nexters/linkllet/config/SwaggerConfiguration.kt
  src/main/kotlin/nexters/linkllet/config/WebMvcConfiguration.kt
  src/main/kotlin/nexters/linkllet/folder/domain/Folder.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderRepository.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderType.kt
  src/main/kotlin/nexters/linkllet/folder/dto/ArticleDtos.kt
  src/main/kotlin/nexters/linkllet/folder/dto/FolderDtos.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderCommandApi.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderQueryApi.kt
  src/main/kotlin/nexters/linkllet/folder/service/FolderService.kt
  src/main/kotlin/nexters/linkllet/member/domain/Member.kt
  src/main/kotlin/nexters/linkllet/member/domain/MemberRepository.kt
  src/main/kotlin/nexters/linkllet/member/dto/MemberDtos.kt
  src/main/kotlin/nexters/linkllet/member/presentation/MemberCommandApi.kt
  src/main/kotlin/nexters/linkllet/member/service/MemberService.kt
  src/main/resources/application.yml
  src/test/kotlin/nexters/linkllet/acceptance/ArticleAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/ArticleStep.kt
  src/test/kotlin/nexters/linkllet/acceptance/CommonStep.kt
  src/test/kotlin/nexters/linkllet/acceptance/FolderAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/FolderStep.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberStep.kt
  src/test/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractorTest.kt
  src/test/kotlin/nexters/linkllet/domain/article/ArticleTest.kt
  src/test/kotlin/nexters/linkllet/domain/folder/FolderTest.kt
  src/test/kotlin/nexters/linkllet/util/AcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/util/DatabaseCleaner.kt
  src/test/kotlin/nexters/linkllet/util/DatabaseCleanerCallback.kt
  src/test/kotlin/nexters/linkllet/util/DatabaseLoader.kt
  src/test/resources/application.yml
Labels: 🔥 버전 업데이트 🔥

#26 feat: article count and date
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/article/domain/Article.kt
  src/main/kotlin/nexters/linkllet/article/domain/Link.kt
  src/main/kotlin/nexters/linkllet/common/domain/BaseTimeEntity.kt
  src/main/kotlin/nexters/linkllet/config/QuerydslConfig.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderQueryRepository.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderQueryRepositoryImpl.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderRepository.kt
  src/main/kotlin/nexters/linkllet/folder/dto/ArticleDtos.kt
  src/main/kotlin/nexters/linkllet/folder/dto/FolderDtos.kt
  src/main/kotlin/nexters/linkllet/folder/service/FolderService.kt
  src/test/kotlin/nexters/linkllet/acceptance/FolderAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/domain/article/ArticleTest.kt
Labels: 🚀 기능 구현 🚀

#31 fix: 링크 길이 제한을 1000자로 변경한다
  src/main/kotlin/nexters/linkllet/article/domain/Article.kt
  src/main/kotlin/nexters/linkllet/article/domain/Link.kt
  src/test/kotlin/nexters/linkllet/domain/article/ArticleTest.kt
Labels: ❗️버그❗️
