Repository Nexters/Linkllet-Server, pull requests merged in 2023-08, with the labels that each got.

#34 feat: 스프링 애플리케이션 TimeZone 설정
  src/main/kotlin/nexters/linkllet/config/TimeZoneConfig.kt
Labels: 🚀 기능 구현 🚀

#37 docs: 기본 Readme 작성
  README.md
Labels: 📖 문서화 📖

#38 version 1.1.0
  README.md
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/article/domain/Article.kt
  src/main/kotlin/nexters/linkllet/article/domain/Link.kt
  src/main/kotlin/nexters/linkllet/common/domain/BaseTimeEntity.kt
  src/main/kotlin/nexters/linkllet/config/QuerydslConfig.kt
  src/main/kotlin/nexters/linkllet/config/TimeZoneConfig.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderQueryRepository.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderQueryRepositoryImpl.kt
  src/main/kotlin/nexters/linkllet/folder/domain/FolderRepository.kt
  src/main/kotlin/nexters/linkllet/folder/dto/ArticleDtos.kt
  src/main/kotlin/nexters/linkllet/folder/dto/FolderDtos.kt
  src/main/kotlin/nexters/linkllet/folder/service/FolderService.kt
  src/main/kotlin/nexters/linkllet/member/domain/Feedback.kt
  src/main/kotlin/nexters/linkllet/member/domain/Feedbacks.kt
  src/main/kotlin/nexters/linkllet/member/domain/Member.kt
  src/main/kotlin/nexters/linkllet/member/dto/MemberDtos.kt
  src/main/kotlin/nexters/linkllet/member/presentation/MemberCommandApi.kt
  src/main/kotlin/nexters/linkllet/member/service/MemberService.kt
  src/main/resources/application.yml
  src/test/kotlin/nexters/linkllet/acceptance/FolderAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberStep.kt
  src/test/kotlin/nexters/linkllet/domain/article/ArticleTest.kt
  src/test/kotlin/nexters/linkllet/domain/member/MemberTest.kt
Labels: 🔥 버전 업데이트 🔥

#39 feat: create search
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/article/domain/ArticleQueryRepository.kt
  src/main/kotlin/nexters/linkllet/folder/dto/ArticleDtos.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderQueryApi.kt
  src/main/kotlin/nexters/linkllet/folder/service/FolderService.kt
  src/test/kotlin/nexters/linkllet/acceptance/ArticleAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/ArticleStep.kt
Labels: 🚀 기능 구현 🚀

#41 feat: 디바이스 ID를 JWT로 마이그레이션한다
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/common/exception/dto/ErrorDtos.kt
  src/main/kotlin/nexters/linkllet/common/support/AuthorizationExtractor.kt
  src/main/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractor.kt
  src/main/kotlin/nexters/linkllet/common/support/JwtProvider.kt
  src/main/kotlin/nexters/linkllet/common/support/LoginUserEmail.kt
  src/main/kotlin/nexters/linkllet/common/support/LoginUserResolver.kt
  src/main/kotlin/nexters/linkllet/config/AppConfig.kt
  src/main/kotlin/nexters/linkllet/config/JwtConfigProperties.kt
  src/main/kotlin/nexters/linkllet/config/SwaggerConfiguration.kt
  src/main/kotlin/nexters/linkllet/config/WebMvcConfiguration.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderCommandApi.kt
  src/main/kotlin/nexters/linkllet/folder/presentation/FolderQueryApi.kt
  src/main/kotlin/nexters/linkllet/folder/service/FolderService.kt
  src/main/kotlin/nexters/linkllet/member/domain/Member.kt
  src/main/kotlin/nexters/linkllet/member/domain/MemberRepository.kt
  src/main/kotlin/nexters/linkllet/member/dto/MemberDtos.kt
  src/main/kotlin/nexters/linkllet/member/presentation/MemberCommandApi.kt
  src/main/kotlin/nexters/linkllet/member/service/AuthService.kt
  src/main/kotlin/nexters/linkllet/member/service/MemberService.kt
  src/main/resources/application.yml
  src/test/kotlin/nexters/linkllet/acceptance/ArticleAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/ArticleStep.kt
  src/test/kotlin/nexters/linkllet/acceptance/FolderAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/FolderStep.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberAcceptanceTest.kt
  src/test/kotlin/nexters/linkllet/acceptance/MemberStep.kt
  src/test/kotlin/nexters/linkllet/common/support/AuthorizationExtractorTest.kt
  src/test/kotlin/nexters/linkllet/common/support/DeviceHeaderExtractorTest.kt
  src/test/kotlin/nexters/linkllet/common/support/JwtProviderTest.kt
  src/test/kotlin/nexters/linkllet/domain/member/MemberTest.kt
  src/test/kotlin/nexters/linkllet/util/DatabaseLoader.kt
  src/test/resources/application.yml
Labels: 🚀 기능 구현 🚀, 🎲 API 변경 🎲

#42 feat: Apple OAuth를 구현한다
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/common/exception/CommonExceptionHandler.kt
  src/main/kotlin/nexters/linkllet/common/support/JwtProvider.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleClaimsValidator.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleClient.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleJwtParser.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleOAuthUserProvider.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/ApplePlatformUserDtos.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/ApplePublicKeys.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/PublicKeyGenerator.kt
  src/main/kotlin/nexters/linkllet/config/AppConfig.kt
  src/main/kotlin/nexters/linkllet/config/AppleOAuthConfigProperties.kt
  src/main/kotlin/nexters/linkllet/config/FeignConfig.kt
  src/main/kotlin/nexters/linkllet/member/dto/MemberDtos.kt
  src/main/kotlin/nexters/linkllet/member/presentation/MemberCommandApi.kt
  src/main/kotlin/nexters/linkllet/member/service/AuthService.kt
  src/main/resources/application.yml
  src/test/kotlin/nexters/linkllet/common/support/apple/AppleClaimsValidatorTest.kt
  src/test/kotlin/nexters/linkllet/common/support/apple/AppleClientTest.kt
  src/test/kotlin/nexters/linkllet/common/support/apple/AppleJwtParserTest.kt
Labels: 🚀 기능 구현 🚀, 🎲 API 변경 🎲

#44 feat: create kakao oauth
  README.md
  build.gradle.kts
  src/main/kotlin/nexters/linkllet/LinklletApplication.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleClaimsValidator.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleOAuthConfigProperties.kt
  src/main/kotlin/nexters/linkllet/common/support/kakao/KakaoClientRequest.kt
  src/main/kotlin/nexters/linkllet/common/support/kakao/KakaoClientResponse.kt
  src/main/kotlin/nexters/linkllet/common/support/kakao/KakaoOAuthConfigProperties.kt
  src/main/kotlin/nexters/linkllet/common/support/kakao/KakaoOAuthUserProvider.kt
  src/main/kotlin/nexters/linkllet/common/support/kakao/client/KakaoAccessTokenClient.kt
  src/main/kotlin/nexters/linkllet/common/support/kakao/client/KakaoUserInfoClient.kt
  src/main/kotlin/nexters/linkllet/config/AppConfig.kt
  src/main/kotlin/nexters/linkllet/config/AppleOAuthConfigProperties.kt
  src/main/kotlin/nexters/linkllet/config/JwtConfigProperties.kt
  src/main/kotlin/nexters/linkllet/config/KakaoFeignConfiguration.kt
  src/main/kotlin/nexters/linkllet/member/dto/MemberDtos.kt
  src/main/kotlin/nexters/linkllet/member/presentation/MemberCommandApi.kt
  src/main/kotlin/nexters/linkllet/member/service/AuthService.kt
  src/main/kotlin/nexters/linkllet/member/service/MemberService.kt
  src/main/resources/application.yml
  src/test/kotlin/nexters/linkllet/common/ClientMocksExtension.kt
  src/test/kotlin/nexters/linkllet/common/WireMockClientTest.kt
  src/test/kotlin/nexters/linkllet/common/support/apple/AppleClaimsValidatorTest.kt
  src/test/kotlin/nexters/linkllet/common/support/kakao/KakaoOAuthUserProviderTest.kt
  src/test/kotlin/nexters/linkllet/common/support/kakao/mock/KakaoAuthMocks.kt
  src/test/resources/application.yml
  src/test/resources/payload/get-kakao-acess-token-response.json
  src/test/resources/payload/get-kakao-user-email-response.json
Labels: 🚀 기능 구현 🚀, 🎲 API 변경 🎲

#46 feat: apple oauth nonce 제거
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleClaimsValidator.kt
  src/main/kotlin/nexters/linkllet/common/support/apple/AppleJwtParser.kt
  src/main/kotlin/nexters/linkllet/config/AppleOAuthConfigProperties.kt
  src/test/kotlin/nexters/linkllet/common/support/apple/AppleClaimsValidatorTest.kt
Labels: 🚀 기능 구현 🚀

#48 fix: jwt properties name change
  src/main/kotlin/nexters/linkllet/common/support/JwtProvider.kt
  src/main/kotlin/nexters/linkllet/config/JwtConfigProperties.kt
Labels: ❗️버그❗️
